class CommonText:
    OK = "确定"
    CONFIRM = "确认"
    CANCEL = "取消"
    INFO = "提示"
    ERROR = "错误"
    WARNING = "警告"
    SUCCESS = "成功"
    CONTINUE = "继续"
    DELETE = "删除"
    RENAME = "重命名"
    EDIT = "编辑"
    CREATE = "创建"
    SWITCH = "切换"
    CLEAR = "清空"
    ADD = "添加"
    REMOVE = "移除"
    COPY = "复制"
    CUT = "剪切"
    SAVE = "保存"
    CLOSE = "关闭"
    BROWSE = "浏览..."
    SEARCH = "查询"
    PREVIOUS = "上一张"
    NEXT = "下一张"
    FILE_NAME = "文件名"
    FILE_PATH = "文件路径"
    FILE_SIZE = "文件大小"
    MODIFIED_TIME = "修改时间"
    FILE_NOT_FOUND = "文件已不存在。"
    OPEN_FILE_ERROR = "无法打开文件：\n{file_path}\n{error}"


class FileShowAreaText:
    SELECT_ALL = "全选"
    VIEW = "查看"
    SMALL_ICON = "小图标"
    MEDIUM_ICON = "中等图标"
    LARGE_ICON = "大图标"
    SORT = "排序"
    SORT_BY_NAME = "按文件名"
    SORT_BY_SIZE = "按文件大小"
    SORT_BY_DATE = "按修改日期"
    SORT_RANDOM = "随机排序"
    ASCENDING = "升序"
    DESCENDING = "降序"
    PROPERTIES = "属性"
    FILE_ACTIONS = "文件操作"
    OPEN_WITH_DEFAULT = "系统默认方式打开"
    OPEN_FILE_LOCATION = "打开文件所在位置"
    SELECT_ALL_INVALID = "选中所有失效文件"
    REPAIR_FILE = "修复文件"
    REFRESH = "刷新"
    DELETE_FROM_LIBRARY = "从库中删除"
    MANAGE_TAGS = "管理标签"
    CHOOSE_TARGET_FOLDER = "选择目标文件夹"
    COPY_TAGS_CONFIRM = "是否同步复制标签？"
    RENAME_FILE_TITLE = "重命名文件"
    ENTER_NEW_FILE_NAME = "请输入新的文件名："
    CONFIRM_DELETE_TITLE = "确认删除"
    DELETE_FILES_CONFIRM = "确定要删除选中的文件吗？此操作将在系统层删除文件！"
    DELETE_FROM_LIBRARY_CONFIRM = "确定要从库中删除选中的文件吗？"
    NO_INVALID_SELECTED = "当前没有选中失效文件。"
    CHOOSE_REPAIR_FOLDER = "选择候选文件所在文件夹"
    NO_REPAIR_NEEDED = "当前没有需要修复的失效文件。"
    REPAIR_CANDIDATE_TITLE = "修复: '{file_name}' ({original_path})"
    FILE_PROPERTIES_TITLE = "{file_name} 属性"
    NO_TAGS = "无标签"
    FILE_TAGS = "文件标签"
    DRAG_FILES_OR_FOLDERS = "请拖入文件或文件夹"


class MainWindowText:
    WEB_ENTRY_TITLE = "Web端入口"
    ACCESS_ADDRESS = "访问地址"
    TRAY_SHOW = "显示窗口"
    TRAY_QUIT = "退出"
    START_MENU = "开始"
    TAGBASE_MANAGER = "标签库"
    WEB_ENTRY = "Web端入口"
    MINIMIZE_TO_TRAY = "最小化到托盘"
    MANAGE_TAGS = "管理标签"
    MANAGE_CATEGORIES = "管理类别"
    RESTORE_SEARCH_RESULTS = "返回搜索结果"
    GO_PARENT = "上一级"
    INVALID_EXPRESSION_TITLE = "错误！"
    INVALID_EXPRESSION = "错误的表达式：{tag_expression}\n\n具体原因：{error}"
    OPEN_FOLDER_ERROR = "无法打开文件夹：\n{folder_path}\n{error}"


class TagViewText:
    WINDOW_TITLE = "标签管理"
    REJECT_FOLDER = "不接受文件夹"
    ACCEPT_FOLDER = "接受文件夹"
    NORMAL_MODE = "普通模式"
    QUICK_MODE = "快速模式"
    TAG_INPUT_PLACEHOLDER = "输入标签..."
    SWITCH_VIEW = "切换视图"
    DELETE_TAG = "删除"
    CHANGE_CATEGORY = "修改类别"
    INVALID_CHAR = "存在非法字符: {op}"
    RENAME_TITLE = "重命名"
    ENTER_NEW_TAG_NAME = "输入新标签名称:"
    MERGE_EXISTING_TAG_CONFIRM = "'{new_name}' 标签已存在，继续将合并标签，是否继续？"
    CHANGE_CATEGORY_TITLE = "修改类别"
    SELECT_OR_ENTER_CATEGORY = "选择或输入新类别名称:"
    CATEGORY_NOT_FOUND = "'{category}' 类别不存在"
    ADD_SUCCESS = "添加成功"
    DELETE_SUCCESS = "删除成功"
    SINGLE_FILE_VIEW = "单文件视图"
    MULTI_FILE_VIEW = "多文件视图"


class CategoryManagerText:
    WINDOW_TITLE = "标签类别管理"
    ADD_CATEGORY = "添加类别"
    MOVE_UP = "上移"
    MOVE_DOWN = "下移"
    TAG_LIST = "标签列表"
    TAG_LIST_WITH_CATEGORY = "标签列表 - {category}"
    ADD_TAG = "添加标签"
    SET_COLOR = "设置颜色"
    SET_NORMAL_CATEGORY = "设为普通类别"
    SET_FILTER_CATEGORY = "设为筛选类别"
    FILE_TYPE_CATEGORY = "文件类型"
    REMOVE_TAG = "移除标签"
    ADD_CATEGORY_TITLE = "添加类别"
    ENTER_NEW_CATEGORY_NAME = "输入新类别名称:"
    CATEGORY_EXISTS = "类别已存在！"
    FILE_TYPE_RENAME_FORBIDDEN = "“文件类型” 类别不允许重命名！"
    EDIT_CATEGORY_TITLE = "编辑类别"
    FILE_TYPE_DELETE_FORBIDDEN = "“文件类型” 类别不允许删除！"
    CONFIRM_DELETE_TITLE = "确认删除"
    CONFIRM_DELETE_CATEGORY = "确定要删除类别 '{category}' 吗？"
    SET_CATEGORY_COLOR_TITLE = "设置类别颜色 - {category}"
    COLOR_PREVIEW = "颜色预览"
    HOVER_SUFFIX = " hover"
    INVALID_CHAR = "存在非法字符：{op}"
    ERROR_TITLE = "错误！"
    ADD_TAG_TITLE = "添加标签"
    SELECT_OR_ENTER_TAG = "选择或输入新标签名称:"


class TagbaseManagerText:
    WINDOW_TITLE = "标签库管理"
    CURRENT_TAGBASE = "当前标签库:"
    NAME = "名称"
    PATH = "路径"
    AVAILABLE_TAGBASES = "可用标签库:"
    SIZE = "文件大小"
    ADD_EXISTING_TAGBASE = "从文件添加标签库"
    REPAIR_FROM_BACKUP = "从备份修复"
    UNKNOWN = "未知"
    SELECT_TAGBASE_FIRST = "请先选择一个标签库"
    CREATE_TAGBASE_TITLE = "创建标签库"
    ENTER_NEW_TAGBASE_NAME = "输入新标签库名称:"
    INVALID_NAME = "名称包含非法字符: \\ / : * ? \" < > |"
    CREATED_TAGBASE = "已创建标签库: {name}"
    EDIT_TAGBASE_TITLE = "编辑标签库"
    SELECT_DIRECTORY = "选择目录"
    NAME_EMPTY = "名称不能为空"
    EDIT_COMPLETED = "修改完成"
    EDIT_FAILED = "修改失败: {error}"
    CONFIRM_DELETE_TITLE = "确认删除"
    CONFIRM_DELETE_TAGBASE = "确定要删除标签库 '{name}' 吗?\n此操作不可恢复!"
    DELETE_COMPLETED = "删除完成"
    DELETE_FAILED = "删除失败: {error}"
    SELECT_TAGBASE_FILE = "选择标签库文件"
    TAGBASE_FILE_FILTER = "标签库文件 (*{ext})"
    TAGBASE_ALREADY_LISTED = "标签库 '{file_name}' 已在列表中"
    ADDED_TAGBASE = "已添加标签库: {file_name}"


class SingleFileTagViewText:
    FILE_INFO_HTML = (
        "<div style='color:#314456; line-height:1.6;'>"
        "<div style='font-size:18px; font-weight:600; color:#1f2d3d; margin-bottom:10px;'>{file_name}</div>"
        "<div><span style='color:#6b7b8c;'>文件路径</span><br>{file_path}</div>"
        "<div style='margin-top:10px;'><span style='color:#6b7b8c;'>文件大小</span><br>{file_size}</div>"
        "<div style='margin-top:10px;'><span style='color:#6b7b8c;'>修改时间</span><br>{modified_time}</div>"
        "</div>"
    )


class FileSelectionText:
    WINDOW_TITLE = "文件选择"
    NO_DATA = "没有可供选择的文件组。"
    GROUP_TITLE = "文件组 {index} (共 {count} 个文件)"
    NO_SELECTION = "不选择任何文件"
    PREVIEW_UNAVAILABLE = "无法预览"
    FILE_MISSING = "文件不存在:\n{file_path}"
    SELECT = "选择"
    SELECTED = "选中"
    FILE_NOT_FOUND_TITLE = "文件不存在"
    FILE_GROUP_NOT_FOUND_TITLE = "未找到文件组"
    FILE_GROUP_NOT_FOUND = "文件未包含在任何文件组中：\n{file_path}"
    OPEN_FILE_FAILED_TITLE = "打开文件失败"
    OPEN_FILE_FAILED = "无法打开文件：\n{file_path}\n错误：{error}"


class PresetSelectorText:
    SELECT_PRESET_TYPE = "选择预设类型"
    MANAGE_PRESETS = "⚙️ 管理预设"
    PRESET_TYPE = "预设类型"


class AudioMarkerText:
    CREATE_MARKER = "创建标记"
    EDIT_MARKER = "编辑标记"
    PRESET = "预设"
    COLOR = "颜色:"
    NOTE_CONTENT = "备注内容:"
    NOTE_PLACEHOLDER = "输入标记备注..."
    TIME_SETTINGS = "时间设置"
    START = "开始:"
    END = "结束:"
    TIME_TIP = "只填写开始时间会保存为点标记，填写开始和结束时间会保存为区间标记。"
    NO_PRESETS = "暂无预设，请先在预设管理器中创建预设"
    CHOOSE_MARKER_COLOR = "选择标记颜色"
    AUDIO_NOT_LOADED = "未加载音频文件"
    ENTER_AT_LEAST_ONE_TIME = "请至少输入一个时间"
    UNNAMED_MARKER = "未命名标记"
    END_BEFORE_START = "结束时间不能小于开始时间"
    CREATE = "创建"
